language: node_js
node_js:
- lts/*
- 6
cache:
  directories:
  - "node_modules"
before_script:
- if [ $(echo "$(npm -v 2>&1 | cut -d. -f-2) < 4.2" | bc) -eq 1 ]; then npm run prepare; fi
after_success:
- ./node_modules/.bin/codacy-coverage < coverage/lcov.info
- ./node_modules/.bin/codecov
before_deploy:
- if [ $(echo "$(npm -v 2>&1 | cut -d. -f-2) < 4.2" | bc) -eq 1 ]; then npm run prepare; fi
deploy:
  provider: npm
  skip_cleanup: true
  email: n.kimura.cap@gmail.com
  api_key:
    secure: MBCetYp2O986h4hb619jyR5OwI0pktAl3pRJWk9gQnAMXNbJRvhccEuWmS9Wn0w48p18ejFpJqPE6pdosENaSIa9x6jN5kj2EIe1W5Pm7cr6Y6lJEKp/qQ1n7kCUtVdSL0xbgqSfr22sWSUQe+cH7PZAPaNLwrOpj83BwD43dvPDokZgB5gu7mZJM+XWyHThKXGLyu83/snQ+pbqrsuZ4A+ToaO6Cy51+7JGPuDi3QAiAbQ5+0/UrjCxVzg1qLPFE6Oio1AqzojvdIyvzozX2QaPQ5EZIBaO3CNAIrhbXRAPmBU5HepargjqRMmhoLLuyan5r7I5Ts8N0h1/Dv2c4U9+ow4fD0TT7cwuT6lJdqgpDqnu1WGozF/0g2F/y8M6rJHlLpSE4lJhfkhLazAz4Eg2O0mufz8wxm+YHDpilKAe6KoPZuiBAZGBO5VjGirZeC4R8wSQzABCLqikIY5koaYkOS8a/3L9J15bLObFiMkL7Bb3ZGXRCoGpWQFnvuiBj39e3BKxJ8FPzKqSrBf7wa4bgAqvJeEJfojJZ9KtNMKKCif+I7ydcR9+knIPk3ah90RPLG9SBbXnVabcyO8NdT2P56Y3iFHyimPY0FjWHJEsl4YauHjmVp1xHnWUpjxNRoA36dcFti/Do30ZEZ66SiBmfLbVG4s350AWWDBCdls=
  on:
    tags: true
    repo: naokikimura/msgpack-rpc-lite
notifications:
  slack:
    secure: vb2VHxsFpRYIoGtuDdUgmSKSj/ASk/SgGBPb5qJdfCBlo0pPdK0Gw9Wqbr4vGm7XBwGocbz4V/E68Y5dHPZP8tXwxNH8bLXX7vj/9qe2J3Kx4jH76UaSvpkoB+1mJqwOU/WUfmWH8xanmQHDqxXFOy+nuMVvvY8JwUu4Yw6zmmTeUubRiXEwsXtm9OVmvc+TxJII4saK0a8P3SXzQ2nOswSGFH6fMwiBh7RzIXJ74vEtV56L4MutFBs/6VFcbZKurabiaKduMDORQ+JENpuyzlOZUZYc8tMY33f6luIjfcC3xYd82ihy05+FUoSFNKjYkna7zhoXybNy7zKHt0XwyY86zcJxNF4DWiRSlMlxR8kos54tg80753LuIiLD3Xkyi2u3DQO09A3J5eE5VILMtVNWXgVWeXTHiudL7FNckBo3N2D9RSCGeDZeXLtjq17nnbUlT0/qwrW/u7KPfEt4Dt8D7jyB0fbhJuI+zPctgriL4nBQSENu+IHPbInWhGyvB5DFEkzg4wZDsLdnSohyWj1LAVrqZ2h9b7B/AcTtbZLis/jg3thdK71TgjVxzirA7rrCiHinuKPHlWiVddlZop98NOSZkAfJLd+5+Y/1JpqBBFD5ljf1DNiOtcnvN/mAVNbVsy/jUCyqViWDxCAQfwe0XfiZb6UNEcFnJYf2XAQ=
